accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view
from . import views

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", views.signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect


def redirect_to_home(request):
    return redirect("home")


# url patterns boiii
urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", redirect_to_home),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    receipt_list,
    create_receipt,
    category_list,
    account_list,
    create_category,
    create_account,
)

urlpatterns = [
    path("", receipt_list, name="home"),
    path("create/", create_receipt, name="create_receipt"),
    path("categories/", category_list, name="category_list"),
    path("accounts/", account_list, name="account_list"),
    path("categories/create/", create_category, name="create_category"),
    path("accounts/create/", create_account, name="create_account"),
]

accounts/models.py
from django.db import models

receipts/models.py
from django.db import models
from django.contrib.auth.models import User


# create models
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="categories"
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="accounts"
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="receipts"
    )
    category = models.ForeignKey(
        ExpenseCategory,
        on_delete=models.CASCADE,
        related_name="receipts",
        null=True,
    )
    account = models.ForeignKey(
        Account, on_delete=models.CASCADE, related_name="receipts", null=True
    )

    def __str__(self):
        return f"{self.vendor} - {self.total}"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=150)
    password1 = forms.CharField(max_length=150, widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=150, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "password1", "password2")

receipts/forms.py
from django import forms
from receipts.models import Receipt, ExpenseCategory, Account


class ReceiptForm(forms.ModelForm):
    class Meta:
        model = Receipt
        fields = ["vendor", "total", "tax", "date", "category", "account"]


class ExpenseCategoryForm(forms.ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = ["name"]


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ("name", "number")

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from .forms import LoginForm
from django.contrib.auth.models import User


@require_http_methods(["GET", "POST"])
def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse("home"))
    else:
        form = LoginForm()
    return render(request, "accounts/login.html", {"form": form})


def logout_view(request):
    logout(request)
    return redirect("login")


def signup(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        password_confirmation = request.POST["password_confirmation"]
        if password != password_confirmation:
            error = "The passwords do not match"
            return render(
                request, "registration/signup.html", {"error": error}
            )
        else:
            user = User.objects.create_user(
                username=username, password=password
            )
            login(request, user)
            return redirect("home")
    else:
        return render(request, "registration/signup.html")

receipts/views.py
from django.shortcuts import render, redirect
from receipts.models import Receipt, ExpenseCategory, Account
from django.contrib.auth.decorators import login_required
from receipts.forms import ReceiptForm, ExpenseCategoryForm, AccountForm
from django.db.models import Count

# My views v


@login_required
def receipt_list(request):
    receipts = Receipt.objects.filter(purchaser=request.user)
    context = {"receipts": receipts}
    return render(request, "receipts/list.html", context)


@login_required
def create_receipt(request):
    if request.method == "POST":
        form = ReceiptForm(request.POST)
        if form.is_valid():
            receipt = form.save(commit=False)
            receipt.purchaser = request.user
            receipt.save()
            return redirect("home")
    else:
        form = ReceiptForm()
    return render(request, "receipts/create.html", {"form": form})


@login_required
def category_list(request):
    categories = ExpenseCategory.objects.filter(owner=request.user).annotate(
        receipt_count=Count("receipts")
    )
    context = {"categories": categories}
    return render(request, "receipts/categories/list.html", context)


@login_required
def account_list(request):
    accounts = Account.objects.filter(owner=request.user).annotate(
        receipt_count=Count("receipts")
    )
    context = {"accounts": accounts}
    return render(request, "receipts/accounts/list.html", context)


@login_required
def create_category(request):
    if request.method == "POST":
        form = ExpenseCategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.owner = request.user
            category.save()
            return redirect("category_list")
    else:
        form = ExpenseCategoryForm()
    return render(request, "receipts/categories/create.html", {"form": form})


@login_required
def create_account(request):
    if request.method == "POST":
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.owner = request.user
            account.save()
            return redirect("account_list")
    else:
        form = AccountForm()
    return render(request, "receipts/accounts/create.html", {"form": form})

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
</head>

<body>
    <main>
        <div>
            <h1>Login</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Login</button>
            </form>
        </div>
    </main>
</body>

</html>

receipts/templates/navigation.html
<nav>
    {% if user.is_authenticated %}
    <ul>
        <li><a href="{% url 'home' %}">Receipts</a></li>
        <li><a href="{% url 'create_receipt' %}">Create Receipt</a></li>
        <li><a href="{% url 'category_list' %}">Categories</a></li>
        <li><a href="{% url 'create_category' %}">Create Category</a></li>
        <li><a href="{% url 'account_list' %}">Accounts</a></li>
        <li><a href="{% url 'create_account' %}">Create Account</a></li>
    </ul>
    {% endif %}
</nav>

receipts/templates/receipts/accounts/create.html
{% include 'navigation.html' %}
<!DOCTYPE html>
<html>

<head>
    <title>Create Account</title>
</head>

<body>
    <main>
        <div>
            <h1>Create Account</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
</body>

</html>

receipts/templates/receipts/accounts/list.html
{% include 'navigation.html' %}
<!DOCTYPE html>
<html>

<head>
    <title>Accounts</title>
</head>

<body>
    <h1>Accounts</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Receipt Count</th>
            </tr>
        </thead>
        <tbody>
            {% for account in accounts %}
            <tr>
                <td>{{ account.name }}</td>
                <td>{{ account.number }}</td>
                <td>{{ account.receipt_count }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>

</html>

receipts/templates/receipts/categories/create.html
{% include 'navigation.html' %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Create Category</title>
</head>

<body>
    <main>
        <div>
            <h1>Create Category</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
</body>

</html>

receipts/templates/receipts/categories/list.html
{% include 'navigation.html' %}
<!DOCTYPE html>
<html>

<head>
    <title>Expense Categories</title>
</head>

<body>
    <h1>Expense Categories</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Receipt Count</th>
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
            <tr>
                <td>{{ category.name }}</td>
                <td>{{ category.receipt_count }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>

</html>

receipts/templates/receipts/create.html
{% include 'navigation.html' %}
<!DOCTYPE html>
<html>

<head>
    <title>Create Receipt</title>
</head>

<body>
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method="post">
                {% csrf_token %}
                <div>
                    <label for="id_vendor">Vendor:</label>
                    <input type="text" name="vendor" id="id_vendor" maxlength="150" required>
                </div>
                <div>
                    <label for="id_total">Total:</label>
                    <input type="number" name="total" id="id_total" step="0.01" required>
                </div>
                <div>
                    <label for="id_tax">Tax:</label>
                    <input type="number" name="tax" id="id_tax" step="0.01" required>
                </div>
                <div>
                    <label for="id_date">Date:</label>
                    <input type="date" name="date" id="id_date" required>
                </div>
                <div>
                    <label for="id_category">Category:</label>
                    <select name="category" id="id_category">
                        {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div>
                    <label for="id_account">Account:</label>
                    <select name="account" id="id_account">
                        {% for account in accounts %}
                        <option value="{{ account.id }}">{{ account.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
</body>

</html>

receipts/templates/receipts/list.html
{% include 'navigation.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>My Receipts</title>
</head>

<body>
    <header>
    </header>
    <main>
        <h1>My Receipts</h1>
        <table>
            <thead>
                <tr>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Account</th>
                </tr>
            </thead>
            <tbody>
                {% for receipt in receipts %}
                <tr>
                    <td>{{ receipt.vendor }}</td>
                    <td>{{ receipt.total }}</td>
                    <td>{{ receipt.tax }}</td>
                    <td>{{ receipt.date|date:'m/d/YY'}}</td>
                    <td>{{ receipt.category.name }}</td>
                    <td>{{ receipt.account.name }}</td>
                </tr>
                {% endfor %}
                <tr>
                    <td>ZZZZZZ</td>
                    <td>20.000</td>
                    <td>100.000</td>
                    <td>04/20/23</td>
                    <td>Category 1</td>
                    <td>Noors Account</td>
                </tr>
            </tbody>
        </table>
    </main>
    <footer>
        <p>&copy; 2023 My Receipts App</p>
    </footer>
</body>

</html>